import './globals.css'
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import {ThemeContextProvider} from "@/context/ThemeContext"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ThemeContextProvider>
      <html lang="en" className="">
        <body>
           <Navbar/>
            {children}
           <Footer/>
        </body>
      </html>
    </ThemeContextProvider>
  )
}
